MiParcialito/Controllers/cursosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiParcialito.Models;

namespace MiParcialito.Controllers
{
    public class cursosController : Controller
    {
        private AV100520Entities db = new AV100520Entities();


        public ActionResult Index()
        {
            if (Session["IsAdmin"] != null)
            {
                if (Session["IsAdmin"].ToString() == "True")
                {
                    var cursos = db.cursos.Include(c => c.docentes);
                    return View(cursos.ToList());
                }
                else if (Session["IsAdmin"].ToString() == "False")
                {
                    return RedirectToAction("Index", "Access");
                }
                else
                {
                    return RedirectToAction("AccessDenied", "Home");
                }
            }
            else
            {

                return RedirectToAction("Index", "Access");
            }
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cursos cursos = db.cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            return View(cursos);
        }


        public ActionResult Create()
        {
            ViewBag.idDocente = new SelectList(db.docentes, "idDocente", "nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cursoID,nombreCurso,idDocente")] cursos cursos)
        {
            if (ModelState.IsValid)
            {
                db.cursos.Add(cursos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idDocente = new SelectList(db.docentes, "idDocente", "nombre", cursos.idDocente);
            return View(cursos);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cursos cursos = db.cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDocente = new SelectList(db.docentes, "idDocente", "nombre", cursos.idDocente);
            return View(cursos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cursoID,nombreCurso,idDocente")] cursos cursos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cursos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDocente = new SelectList(db.docentes, "idDocente", "nombre", cursos.idDocente);
            return View(cursos);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cursos cursos = db.cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            return View(cursos);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cursos cursos = db.cursos.Find(id);
            db.cursos.Remove(cursos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiParcialito/Controllers/docentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiParcialito.Models;

namespace MiParcialito.Controllers
{
    public class docentesController : Controller
    {
        private AV100520Entities db = new AV100520Entities();

        public ActionResult Index(ActionExecutingContext filterContext)
        {
            if (Session["IsAdmin"] != null)
            {
                if (Session["IsAdmin"].ToString() == "True")
                {
                    return View(db.docentes.ToList());
                }
                else if (Session["IsAdmin"].ToString() == "False")
                {
                    return RedirectToAction("Index", "Access");
                }
                else
                {
                    return RedirectToAction("AccessDenied", "Home");
                }
            }
            else
            {

                return RedirectToAction("Index", "Access");
            }


        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            docentes docentes = db.docentes.Find(id);
            if (docentes == null)
            {
                return HttpNotFound();
            }
            return View(docentes);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idDocente,nombre")] docentes docentes)
        {
            if (ModelState.IsValid)
            {
                db.docentes.Add(docentes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(docentes);
        }

        // GET: docentes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            docentes docentes = db.docentes.Find(id);
            if (docentes == null)
            {
                return HttpNotFound();
            }
            return View(docentes);
        }

        // POST: docentes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idDocente,nombre")] docentes docentes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(docentes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(docentes);
        }

        // GET: docentes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            docentes docentes = db.docentes.Find(id);
            if (docentes == null)
            {
                return HttpNotFound();
            }
            return View(docentes);
        }

        // POST: docentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            docentes docentes = db.docentes.Find(id);
            db.docentes.Remove(docentes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiParcialito/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiParcialito.Models;
using BCrypt.Net;

namespace MiParcialito.Controllers
{
    public class usersController : Controller
    {
        private AV100520Entities db = new AV100520Entities();

        // GET: users
        public ActionResult Index(ActionExecutingContext filterContext)
        {
            if (Session["IsAdmin"].ToString() == "True")
            {
                var user = db.user.Include(u => u.roles).Include(u => u.status);
                return View(user.ToList());
            }
            else if (Session["IsAdmin"].ToString() == "False")
            {
                return RedirectToAction("Index", "Access");
            }

            else
            {

                return RedirectToAction("AccessDenied", "Home");
            }

        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            ViewBag.idroles = new SelectList(db.roles, "idRoles", "nombre");
            ViewBag.idStatus = new SelectList(db.status, "idStatus", "nombre");
            return View();
        }

        // POST: users/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idUser,email,password,edad,fecha_nacimiento,idroles,idStatus")] user user)
        {
            if (ModelState.IsValid)
            {
                // Encriptar la contraseña antes de guardarla
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(user.password);
                user.password = hashedPassword;

                db.user.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idroles = new SelectList(db.roles, "idRoles", "nombre", user.idroles);
            ViewBag.idStatus = new SelectList(db.status, "idStatus", "nombre", user.idStatus);
            return View(user);
        }

        // GET: users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.idroles = new SelectList(db.roles, "idRoles", "nombre", user.idroles);
            ViewBag.idStatus = new SelectList(db.status, "idStatus", "nombre", user.idStatus);
            return View(user);
        }

        // POST: users/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idUser,email,password,edad,fecha_nacimiento,idroles,idStatus")] user user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idroles = new SelectList(db.roles, "idRoles", "nombre", user.idroles);
            ViewBag.idStatus = new SelectList(db.status, "idStatus", "nombre", user.idStatus);
            return View(user);
        }

        // GET: users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user user = db.user.Find(id);
            db.user.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiParcialito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "cursos", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["IsAdmin"] != null && Session["IsAdmin"].ToString() == "True")
                    {

                        <li>@Html.ActionLink("Usuarios", "index", "users", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Materias", "index", "cursos", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Docentes", "index", "docentes", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Materias", "index", "cursos", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Cerrar sesión", "Logout", "Access", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (Session["IsAdmin"] != null && Session["IsAdmin"].ToString() == "False")
                    { 
                        <li>@Html.ActionLink("Materias", "index", "inscripciones", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Cerrar sesión", "Logout", "Access", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiParcialito/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "cursos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Registrarse", "index", "register", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Iniciar sesion", "index", "Access", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>